import { StyleSheet } from 'react-native'

export const demoStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0F0C29',
  },
  gradient: {
    ...StyleSheet.absoluteFillObject,
  },
  safeArea: {
    flex: 1,
    paddingHorizontal: 24,
  },
  header: {
    marginTop: 8,
    marginBottom: 20,
    gap: 10,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.12)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  title: {
    fontSize: 24,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  card: {
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
    padding: 20,
    alignItems: 'center',
    gap: 12,
  },
  contentCard: {
    marginTop: 16,
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
    padding: 12,
    flex: 1,
  },
  iconCircle: {
    width: 72,
    height: 72,
    borderRadius: 24,
    backgroundColor: 'rgba(118, 75, 162, 0.5)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#FFFFFF',
    textAlign: 'center',
  },
  cardSubtitle: {
    fontSize: 14,
    color: 'rgba(255,255,255,0.7)',
    textAlign: 'center',
  },
  errorText: {
    marginTop: 8,
    fontSize: 13,
    color: '#FCA5A5',
    textAlign: 'center',
  },
  slideCard: {
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
    padding: 16,
  },
  slideBadge: {
    alignSelf: 'flex-start',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: 'rgba(139,124,246,0.2)',
    marginBottom: 10,
  },
  slideBadgeText: {
    color: '#C7BFFF',
    fontSize: 12,
    fontWeight: '600',
  },
  slideTitle: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 10,
  },
  slideControls: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  slideNavButton: {
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.12)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  slideNavButtonDisabled: {
    opacity: 0.4,
  },
  slideDots: {
    flexDirection: 'row',
    gap: 6,
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
  },
  slideDot: {
    width: 8,
    height: 8,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.25)',
  },
  slideDotActive: {
    width: 18,
    backgroundColor: '#8B7CF6',
  },
  problemCard: {
    flexDirection: 'row',
    gap: 12,
    padding: 14,
    borderRadius: 14,
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
  },
  problemIndex: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: 'rgba(249,115,22,0.3)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  problemIndexText: {
    color: '#FDBA74',
    fontWeight: '700',
  },
  sectionTitle: {
    color: '#FCD34D',
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 4,
  },
  interactiveCard: {
    padding: 14,
    borderRadius: 14,
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
    gap: 8,
  },
  interactiveTitle: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
  },
  interactiveHeader: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    gap: 8,
  },
  toggleButton: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 10,
    backgroundColor: 'rgba(99,102,241,0.2)',
    borderWidth: 1,
    borderColor: 'rgba(99,102,241,0.5)',
    alignSelf: 'flex-start',
  },
  toggleButtonText: {
    color: '#C7BFFF',
    fontSize: 12,
    fontWeight: '600',
  },
  miniLabel: {
    color: '#C7BFFF',
    fontSize: 12,
    fontWeight: '600',
  },
  stepRow: {
    flexDirection: 'row',
    gap: 10,
    alignItems: 'flex-start',
  },
  stepIndex: {
    color: '#FCD34D',
    fontSize: 12,
    fontWeight: '700',
    width: 18,
  },
  stepDescription: {
    color: 'rgba(255,255,255,0.7)',
    fontSize: 12,
    marginBottom: 2,
  },
  formulaGrid: {
    gap: 12,
    flexDirection: 'column',
  },
  formulaCard: {
    width: '100%',
    padding: 12,
    borderRadius: 14,
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
    gap: 8,
  },
  formulaLabel: {
    color: '#C7BFFF',
    fontWeight: '700',
  },
  testCard: {
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
    padding: 16,
    gap: 12,
  },
  testHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  testProgress: {
    color: '#FFFFFF',
    fontWeight: '700',
  },
  variantText: {
    color: '#C7BFFF',
    fontSize: 12,
    fontWeight: '600',
  },
  optionButton: {
    flexDirection: 'row',
    gap: 10,
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
    alignItems: 'center',
  },
  optionButtonActive: {
    backgroundColor: 'rgba(108,99,255,0.3)',
    borderColor: 'rgba(108,99,255,0.7)',
  },
  optionLabel: {
    width: 24,
    height: 24,
    borderRadius: 8,
    textAlign: 'center',
    textAlignVertical: 'center',
    backgroundColor: 'rgba(255,255,255,0.12)',
    color: '#E5E7EB',
    fontWeight: '700',
  },
  optionLabelActive: {
    color: '#FFFFFF',
    backgroundColor: 'rgba(108,99,255,0.8)',
  },
  nextButton: {
    marginTop: 10,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
    backgroundColor: '#6C63FF',
  },
  nextButtonText: {
    color: '#FFFFFF',
    fontWeight: '700',
  },
  resultCard: {
    alignItems: 'center',
    gap: 10,
    padding: 20,
    borderRadius: 16,
    backgroundColor: 'rgba(16,185,129,0.2)',
    borderWidth: 1,
    borderColor: 'rgba(16,185,129,0.4)',
  },
  resultTitle: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '700',
  },
  resultScore: {
    color: '#FBBF24',
    fontSize: 36,
    fontWeight: '800',
  },
  resultMeta: {
    color: '#D1FAE5',
    fontSize: 14,
  },
  emptyCard: {
    padding: 20,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
    backgroundColor: 'rgba(255,255,255,0.06)',
  },
  emptyText: {
    color: 'rgba(255,255,255,0.7)',
    textAlign: 'center',
  },
  simCard: {
    flexDirection: 'row',
    gap: 12,
    padding: 14,
    borderRadius: 14,
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
    alignItems: 'center',
  },
  simBadge: {
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: 'rgba(124,115,255,0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  simTitle: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '700',
  },
  simSubtitle: {
    color: 'rgba(255,255,255,0.65)',
    fontSize: 12,
    marginTop: 2,
  },
  simHeader: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
  },
  simBack: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 10,
    backgroundColor: 'rgba(255,255,255,0.12)',
  },
  simBackText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '600',
  },
})
